version: '3'
services:
  influx:
    image: influxdb:1.5.4-alpine
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - "influxdb_data:/var/lib/influxdb"
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_DB: sensors
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: user
      INFLUXDB_PASSWORD: password

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
    volumes:
      - "grafana_data:/var/lib/grafana"

volumes:
  influxdb_data:
  grafana_data:
